sudo: false

language: node_js

node_js:
  - "6"


env:
  matrix:
    - TEST_TYPE=dev
    - TEST_TYPE=build


script:
  - |
    if [ "$TEST_TYPE" = dev ]; then
      npm run dev
    elif [ "$TEST_TYPE" = build ]; then
      npm run build && \
      node server.js
    fi
